<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Editable image positions (see PROJECT_REQUIREMENTS.md §12.4)
    |--------------------------------------------------------------------------
    */
    'positions' => [
        'brand.logo_header' => 'Header logo',
        'brand.favicon' => 'Favicon',
        'hero.home.main' => 'Home hero main',
        'hero.home.info_1' => 'Home hero info image 1',
        'hero.home.info_2' => 'Home hero info image 2',
        'home.about.image_1' => 'Home about image 1',
        'home.about.image_1_slide_2' => 'Home about image 1 - slide 2',
        'home.about.image_2' => 'Home about image 2',
        'home.about.image_2_slide_2' => 'Home about image 2 - slide 2',
        'home.about.video_poster' => 'Home about — video poster / intro image',
        'home.services.land' => 'Home services — Land',
        'home.services.host' => 'Home services — Host',
        'home.services.minerals' => 'Home services — Minerals',
        'home.services.power' => 'Home services — Power',
        'sector.land.hero' => 'Minh Long Land hero',
        'sector.land.hero_client_author_1' => 'Minh Long Land hero client author 1',
        'sector.land.hero_client_author_2' => 'Minh Long Land hero client author 2',
        'sector.land.hero_client_author_3' => 'Minh Long Land hero client author 3',
        'sector.land.hero_video_poster' => 'Minh Long Land hero video poster',
        'sector.land.about_image' => 'Minh Long Land about image',
        'sector.land.what_we_image_1' => 'Minh Long Land what-we image 1',
        'sector.land.what_we_shape_1' => 'Minh Long Land what-we shape 1',
        'sector.land.what_we_image_2' => 'Minh Long Land what-we image 2',
        'sector.land.what_we_shape_2' => 'Minh Long Land what-we shape 2',
        'sector.land.what_we_body_image' => 'Minh Long Land what-we body image',
        'sector.land.projects_image_1' => 'Minh Long Land project image 1',
        'sector.land.projects_image_2' => 'Minh Long Land project image 2',
        'sector.land.why_choose_image' => 'Minh Long Land why-choose image',
        'sector.land.feature_image_1' => 'Minh Long Land feature image 1',
        'sector.land.feature_image_2' => 'Minh Long Land feature image 2',
        'sector.land.feature_image_3' => 'Minh Long Land feature image 3',
        'sector.land.feature_image_4' => 'Minh Long Land feature image 4',
        'sector.land.cta_image' => 'Minh Long Land CTA image',
        'sector.land.testimonial_author_1' => 'Minh Long Land testimonial author 1',
        'sector.land.testimonial_author_2' => 'Minh Long Land testimonial author 2',
        'sector.host.hero' => 'Minh Long Host hero',
        'sector.host.hero_client_author_1' => 'Minh Long Host hero client author 1',
        'sector.host.hero_client_author_2' => 'Minh Long Host hero client author 2',
        'sector.host.hero_client_author_3' => 'Minh Long Host hero client author 3',
        'sector.host.hero_video_poster' => 'Minh Long Host hero video poster',
        'sector.host.about_image' => 'Minh Long Host about image',
        'sector.host.what_we_image_1' => 'Minh Long Host what-we image 1',
        'sector.host.what_we_shape_1' => 'Minh Long Host what-we shape 1',
        'sector.host.what_we_image_2' => 'Minh Long Host what-we image 2',
        'sector.host.what_we_shape_2' => 'Minh Long Host what-we shape 2',
        'sector.host.what_we_body_image' => 'Minh Long Host what-we body image',
        'sector.host.projects_image_1' => 'Minh Long Host project image 1',
        'sector.host.projects_image_2' => 'Minh Long Host project image 2',
        'sector.host.why_choose_image' => 'Minh Long Host why-choose image',
        'sector.host.feature_image_1' => 'Minh Long Host feature image 1',
        'sector.host.feature_image_2' => 'Minh Long Host feature image 2',
        'sector.host.feature_image_3' => 'Minh Long Host feature image 3',
        'sector.host.feature_image_4' => 'Minh Long Host feature image 4',
        'sector.host.cta_image' => 'Minh Long Host CTA image',
        'sector.host.testimonial_author_1' => 'Minh Long Host testimonial author 1',
        'sector.host.testimonial_author_2' => 'Minh Long Host testimonial author 2',
        'sector.power.hero' => 'Minh Long Power hero',
        'sector.power.about_image_1' => 'Minh Long Power about image 1',
        'sector.power.about_image_2' => 'Minh Long Power about image 2',
        'sector.power.service_image_1' => 'Minh Long Power service image 1',
        'sector.power.service_image_2' => 'Minh Long Power service image 2',
        'sector.power.service_image_3' => 'Minh Long Power service image 3',
        'sector.power.service_image_4' => 'Minh Long Power service image 4',
        'sector.power.what_we_body_image' => 'Minh Long Power what-we body image',
        'sector.power.what_we_content_image' => 'Minh Long Power what-we content image',
        'sector.minerals.hero' => 'Minh Long Minerals hero',
        'sector.minerals.about_image_1' => 'Minh Long Minerals about image 1',
        'sector.minerals.about_image_2' => 'Minh Long Minerals about image 2',
        'sector.minerals.service_image_1' => 'Minh Long Minerals service image 1',
        'sector.minerals.service_image_2' => 'Minh Long Minerals service image 2',
        'sector.minerals.service_image_3' => 'Minh Long Minerals service image 3',
        'sector.minerals.service_image_4' => 'Minh Long Minerals service image 4',
        'sector.minerals.what_we_body_image' => 'Minh Long Minerals what-we body image',
        'sector.minerals.what_we_content_image' => 'Minh Long Minerals what-we content image',
        'about.overview.image_1' => 'About page overview image 1',
        'about.overview.image_2' => 'About page overview image 2',
        'about.overview.video_poster' => 'About page overview video poster',
        'about.approach.image_1' => 'About page approach image 1',
        'about.approach.image_2' => 'About page approach image 2',
        'about.approach.image_3' => 'About page approach image 3',
        'og.default_image' => 'Default Open Graph image',
    ],

    /*
    |--------------------------------------------------------------------------
    | Fallback URLs when no upload exists and no row in site_media_links (path for
    | asset(), or absolute http(s) URL). Seeded via SiteMediaLinkSeeder; blades use
    | SiteMedia::urlOrDefault().
    |--------------------------------------------------------------------------
    */
    'defaults' => [
        'brand.logo_header' => 'frontend/images/logo.png',
        'brand.favicon' => 'frontend/images/favicon.svg',
        'hero.home.main' => 'frontend/images/hero-bg-image.jpg',
        'hero.home.info_1' => 'frontend/images/hero-info-image-1.jpg',
        'hero.home.info_2' => 'frontend/images/hero-info-image-2.jpg',
        'home.about.image_1' => 'frontend/images/about-us-image-1.jpg',
        'home.about.image_1_slide_2' => 'frontend/images/about-us-image-1.jpg',
        'home.about.image_2' => 'frontend/images/about-us-image-2.jpg',
        'home.about.image_2_slide_2' => 'frontend/images/about-us-image-2.jpg',
        'home.about.video_poster' => 'frontend/images/about-intro-video-image.jpg',
        'home.services.land' => 'frontend/images/minhlong-land.png',
        'home.services.host' => 'frontend/images/minhlong-host.jpg',
        'home.services.minerals' => 'frontend/images/minerals/about-quarry-conveyors.png',
        'home.services.power' => 'frontend/images/minhlong-power.jpg',
        'sector.land.hero' => 'frontend/images/hero-image-gold.jpg',
        'sector.land.hero_client_author_1' => 'frontend/images/author-1.jpg',
        'sector.land.hero_client_author_2' => 'frontend/images/author-2.jpg',
        'sector.land.hero_client_author_3' => 'frontend/images/author-3.jpg',
        'sector.land.hero_video_poster' => 'frontend/images/hero-video-image-gold.jpg',
        'sector.land.about_image' => 'frontend/images/about-us-image-gold.png',
        'sector.land.what_we_image_1' => 'frontend/images/what-we-item-image-1-gold.jpg',
        'sector.land.what_we_shape_1' => 'frontend/images/what-we-item-shape-image-1-gold.jpg',
        'sector.land.what_we_image_2' => 'frontend/images/what-we-item-image-2-gold.jpg',
        'sector.land.what_we_shape_2' => 'frontend/images/what-we-item-shape-image-2-gold.jpg',
        'sector.land.what_we_body_image' => 'frontend/images/what-we-item-body-image-gold.png',
        'sector.land.projects_image_1' => 'frontend/images/project-image-1-gold.jpg',
        'sector.land.projects_image_2' => 'frontend/images/project-image-2-gold.jpg',
        'sector.land.why_choose_image' => 'frontend/images/why-choose-item-image-gold.jpg',
        'sector.land.feature_image_1' => 'frontend/images/feature-item-image-1-gold.png',
        'sector.land.feature_image_2' => 'frontend/images/feature-item-image-2-gold.png',
        'sector.land.feature_image_3' => 'frontend/images/feature-item-image-3-gold.png',
        'sector.land.feature_image_4' => 'frontend/images/feature-item-image-4-gold.png',
        'sector.land.cta_image' => 'frontend/images/cta-box-image-gold.png',
        'sector.land.testimonial_author_1' => 'frontend/images/author-1.jpg',
        'sector.land.testimonial_author_2' => 'frontend/images/author-2.jpg',
        'sector.host.hero' => 'frontend/images/minhlong-host-1.png',
        'sector.host.hero_client_author_1' => 'frontend/images/author-1.jpg',
        'sector.host.hero_client_author_2' => 'frontend/images/author-2.jpg',
        'sector.host.hero_client_author_3' => 'frontend/images/author-3.jpg',
        'sector.host.hero_video_poster' => 'frontend/images/minhlong-host-2.png',
        'sector.host.about_image' => 'frontend/images/minhlong-host-3.png',
        'sector.host.what_we_image_1' => 'frontend/images/what-we-item-image-1-gold.jpg',
        'sector.host.what_we_shape_1' => 'frontend/images/what-we-item-shape-image-1-gold.jpg',
        'sector.host.what_we_image_2' => 'frontend/images/minhlong-host-3.png',
        'sector.host.what_we_shape_2' => 'frontend/images/minhlong-host-2.png',
        'sector.host.what_we_body_image' => 'frontend/images/minhlong-host-1.png',
        'sector.host.projects_image_1' => 'frontend/images/minhlong-host-4.jpg',
        'sector.host.projects_image_2' => 'frontend/images/minhlong-host-5.JPG',
        'sector.host.why_choose_image' => 'frontend/images/minhlong-host-3.png',
        'sector.host.feature_image_1' => 'frontend/images/minhlong-host-1.png',
        'sector.host.feature_image_2' => 'frontend/images/minhlong-host-2.png',
        'sector.host.feature_image_3' => 'frontend/images/minhlong-host-3.png',
        'sector.host.feature_image_4' => 'frontend/images/minhlong-host-4.jpg',
        'sector.host.cta_image' => 'frontend/images/minhlong-host-5.JPG',
        'sector.host.testimonial_author_1' => 'frontend/images/author-1.jpg',
        'sector.host.testimonial_author_2' => 'frontend/images/author-2.jpg',
        'sector.power.hero' => 'frontend/images/power-3.jpg',
        'sector.power.about_image_1' => 'frontend/images/power-4.jpg',
        'sector.power.about_image_2' => 'frontend/images/about-us-image-2-silver.png',
        'sector.power.service_image_1' => 'frontend/images/minhlong-power.jpg',
        'sector.power.service_image_2' => 'frontend/images/power-1.jpg',
        'sector.power.service_image_3' => 'frontend/images/power-2.JPG',
        'sector.power.service_image_4' => 'frontend/images/power-4.jpg',
        'sector.power.what_we_body_image' => 'frontend/images/power-1.jpg',
        'sector.power.what_we_content_image' => 'frontend/images/power-2.JPG',
        'sector.minerals.hero' => 'https://images.pexels.com/photos/8247090/pexels-photo-8247090.jpeg',
        'sector.minerals.about_image_1' => 'frontend/images/minerals/about-quarry-conveyors.png',
        'sector.minerals.about_image_2' => 'https://images.pexels.com/photos/4946889/pexels-photo-4946889.jpeg',
        'sector.minerals.service_image_1' => 'https://images.pexels.com/photos/15071424/pexels-photo-15071424.jpeg',
        'sector.minerals.service_image_2' => 'https://images.pexels.com/photos/6553281/pexels-photo-6553281.jpeg',
        'sector.minerals.service_image_3' => 'https://images.pexels.com/photos/33122148/pexels-photo-33122148.jpeg',
        'sector.minerals.service_image_4' => 'https://images.pexels.com/photos/6034140/pexels-photo-6034140.jpeg',
        'sector.minerals.what_we_body_image' => 'https://images.pexels.com/photos/28442180/pexels-photo-28442180.jpeg',
        'sector.minerals.what_we_content_image' => 'https://images.pexels.com/photos/10421754/pexels-photo-10421754.jpeg',
        'about.overview.image_1' => 'frontend/images/about-us-image-1.jpg',
        'about.overview.image_2' => 'frontend/images/about-us-image-2.jpg',
        'about.overview.video_poster' => 'frontend/images/about-intro-video-image.jpg',
        'about.approach.image_1' => 'frontend/images/approach-item-image-1.jpg',
        'about.approach.image_2' => 'frontend/images/approach-item-image-2.jpg',
        'about.approach.image_3' => 'frontend/images/approach-item-image-3.jpg',
        'og.default_image' => 'frontend/images/minhlong-land.png',
    ],
];
